const GETLOGIN = 'GETLOGIN'
const GETEXCELDATALIST = 'GETEXCELDATALIST'
const GETINSURANCEPRODUCTDATALIST = 'GETINSURANCEPRODUCTDATALIST'
const GETDETAILDATALIST = 'GETDETAILDATALIST'
const GETMEBERINFORMATIONDATALIST = 'GETMEBERINFORMATIONDATALIST'
const GETMONTHLYREPORTDATALIST = 'GETMONTHLYREPORTDATALIST'
const GETPERPERFSUMMARYDATALIST = 'GETPERPERFSUMMARYDATALIST'
const GETPLADIFFERENTDATALIST = 'GETPLADIFFERENTDATALIST'
const GETPREWEEkDATALIST = 'GETPREWEEkDATALIST'
const GETQUADIFFERENTDATALIST = 'GETQUADIFFERENTDATALIST'
const GETWAGEDIFFERENTDATALIST = 'GETQUADIFFERENTDATALIST'
const GETTEAMLISTDATALIST = 'GETTEAMLISTDATALIST'
const GETMEBERLISTDATALIST = 'GETMEBERLISTDATALIST'
const GETUSERLIST = 'GETUSERLIST'
const GETPOLICYUSERLIST = 'getPolicyUserList'
const GETPOLICYPERLIST = 'getPolicyPerList'

export {
  GETLOGIN,
  GETEXCELDATALIST,
  GETINSURANCEPRODUCTDATALIST,
  GETDETAILDATALIST,
  GETMEBERINFORMATIONDATALIST,
  GETMONTHLYREPORTDATALIST,
  GETPERPERFSUMMARYDATALIST,
  GETPLADIFFERENTDATALIST,
  GETPREWEEkDATALIST,
  GETQUADIFFERENTDATALIST,
  GETWAGEDIFFERENTDATALIST,
  GETTEAMLISTDATALIST,
  GETMEBERLISTDATALIST,
  GETUSERLIST,
  GETPOLICYUSERLIST,
  GETPOLICYPERLIST
}
