const GETEXCELDATALIST = 'GETEXCELDATALIST'
const GETINSURANCEPRODUCTDATALIST = 'GETINSURANCEPRODUCTDATALIST'
const GETDETAILDATALIST = 'GETDETAILDATALIST'
const GETMEBERINFORMATIONDATALIST = 'GETMEBERINFORMATIONDATALIST'
const GETMONTHLYREPORTDATALIST = 'GETMONTHLYREPORTDATALIST'
const GETPERPERFSUMMARYDATALIST = 'GETPERPERFSUMMARYDATALIST'
const GETPLADIFFERENTDATALIST = 'GETPLADIFFERENTDATALIST'
const GETPREWEEkDATALIST = 'GETPREWEEkDATALIST'
const GETQUADIFFERENTDATALIST = 'GETQUADIFFERENTDATALIST'
const GETWAGEDIFFERENTDATALIST = 'GETQUADIFFERENTDATALIST'
const GETTEAMLISTDATALIST = 'GETTEAMLISTDATALIST'

export {
  GETEXCELDATALIST,
  GETINSURANCEPRODUCTDATALIST,
  GETDETAILDATALIST,
  GETMEBERINFORMATIONDATALIST,
  GETMONTHLYREPORTDATALIST,
  GETPERPERFSUMMARYDATALIST,
  GETPLADIFFERENTDATALIST,
  GETPREWEEkDATALIST,
  GETQUADIFFERENTDATALIST,
  GETWAGEDIFFERENTDATALIST,
  GETTEAMLISTDATALIST

}
